### PR TITLE
Use tox for tests

### PR DESCRIPTION
**Pull request by Changaco**
Simple DevX improvement, came up while I was working on #17.

### CODE REVIEW

**Comment by Changaco** [comment]
Since our tests are very fast it'll be faster and more efficient to run on all python versions in the same build instead of using Travis' test matrix, so I'm going to switch to that.

**Comment by Changaco** [comment]
Ready for review.

Sequential testing is indeed faster, but I had to drop python 3.2.

**Comment by whit537** [comment]
Needs a rebase.

**Comment by Changaco** [comment]
Rebased on master. Travis is green.

**Pull request merged**
